### ISSUE TITLE
항목 삭제 아이콘 수정 및 항목 삭제 시 확인알림 추가 요청

### ISSUE THREAD

**Issue by Wintermaedchen** [eggplantiny/m-journal-nuxt#25]
항목 삭제 아이콘이 빨간 색이라 항목 색도 빨강으로 설정해 놓을 경우 삭제 아이콘이 잘 보이지 않습니다. 
또한 삭제를 누르면 확인알림 없이 바로 삭제되어 실수로 눌렀을 때도 삭제된다는 점이 아쉽습니다.
기록을 빨강으로 설정해 놓았을 때에도 삭제 아이콘이 잘 보이는 것과 삭제 전 확인알림 설정 부탁드립니다.

**Comment by eggplantiny** [comment]
좋은 의견 감사합니다 ☺

**Comment by eggplantiny** [comment]
삭제하기전에 확인 할수있도록 만들었습니다.
감사합니다 😀
