### ISSUE TITLE
Occurred 400 error when submit new diary

### ISSUE THREAD

**Issue by Wintermaedchen** [eggplantiny/m-journal-nuxt#26]
1. '항목을 추가해보세요!' 선택  
2. '기록하기' 칸에 아무 내용도 입력하지 않고 '입력' 누르기
3. 화면 우측 상단에 '에러가 발생했어요 😯 (Error: Request failed with status code 400)' 라고 뜸

![bug](https://user-images.githubusercontent.com/76696805/103369343-3a515980-4b0d-11eb-8f64-8c2179bc460a.PNG)

**Comment by eggplantiny** [comment]
Submit 할때 validation 을 깜빡했네요 ㅎㅎㅎ.....
Validation 을 추가하도록 하겠습니다.
버그제보 감사합니다 😉

**Comment by eggplantiny** [comment]
Title 입력시 Validation 하도록 수정했습니다.
다시한번 리포트 감사드립니다. 😉
